-- Generated by Mocodo 4.2.8

CREATE TABLE CONSULTER (
  PRIMARY KEY (cip, id_reservation),
  cip               VARCHAR(42) NOT NULL,
  id_reservation    VARCHAR(42) NOT NULL,
  date_consultation VARCHAR(42)
);

CREATE TABLE DEPARTEMENT (
  PRIMARY KEY (id_departement),
  id_departement  VARCHAR(42) NOT NULL,
  nom_departement VARCHAR(42)
);

CREATE TABLE LOCAL (
  PRIMARY KEY (pavillon, numero),
  pavillon              VARCHAR(42) NOT NULL,
  numero                VARCHAR(42) NOT NULL,
  categorie             VARCHAR(42),
  capacite              VARCHAR(42),
  code_caracteristiques VARCHAR(42),
  pavillon_2            VARCHAR(42) NOT NULL,
  numero_2              VARCHAR(42) NOT NULL
);

CREATE TABLE MEMBRE (
  PRIMARY KEY (cip),
  cip            VARCHAR(42) NOT NULL,
  nom            VARCHAR(42),
  prenom         VARCHAR(42),
  email          VARCHAR(42),
  id_departement VARCHAR(42) NOT NULL
);

CREATE TABLE POSSEDER (
  PRIMARY KEY (cip, id_statut),
  cip       VARCHAR(42) NOT NULL,
  id_statut VARCHAR(42) NOT NULL
);

CREATE TABLE RESERVATION (
  PRIMARY KEY (id_reservation),
  id_reservation    VARCHAR(42) NOT NULL,
  date_debut        VARCHAR(42),
  date_fin          VARCHAR(42),
  description       VARCHAR(42),
  pavillon          VARCHAR(42) NOT NULL,
  numero            VARCHAR(42) NOT NULL,
  cip_1             VARCHAR(42) NOT NULL,
  date_suppression  VARCHAR(42),
  cip_2             VARCHAR(42) NOT NULL,
  date_modification VARCHAR(42),
  cip_3             VARCHAR(42) NOT NULL,
  date_effectuation VARCHAR(42)
);

CREATE TABLE STATUT (
  PRIMARY KEY (id_statut),
  id_statut  VARCHAR(42) NOT NULL,
  nom_statut VARCHAR(42)
);

ALTER TABLE CONSULTER ADD FOREIGN KEY (id_reservation) REFERENCES RESERVATION (id_reservation);
ALTER TABLE CONSULTER ADD FOREIGN KEY (cip) REFERENCES MEMBRE (cip);

ALTER TABLE LOCAL ADD FOREIGN KEY (pavillon_2, numero_2) REFERENCES LOCAL (pavillon, numero);

ALTER TABLE MEMBRE ADD FOREIGN KEY (id_departement) REFERENCES DEPARTEMENT (id_departement);

ALTER TABLE POSSEDER ADD FOREIGN KEY (id_statut) REFERENCES STATUT (id_statut);
ALTER TABLE POSSEDER ADD FOREIGN KEY (cip) REFERENCES MEMBRE (cip);

ALTER TABLE RESERVATION ADD FOREIGN KEY (cip_3) REFERENCES MEMBRE (cip);
ALTER TABLE RESERVATION ADD FOREIGN KEY (cip_2) REFERENCES MEMBRE (cip);
ALTER TABLE RESERVATION ADD FOREIGN KEY (cip_1) REFERENCES MEMBRE (cip);
ALTER TABLE RESERVATION ADD FOREIGN KEY (pavillon, numero) REFERENCES LOCAL (pavillon, numero);
